//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.PBMS
{

    public partial class BenefitType : XPLiteObject
    {
        string fID_BenefitType;
        [Key]
        [Size(10)]
        public string ID_BenefitType
        {
            get { return fID_BenefitType; }
            set { SetPropertyValue<string>("ID_BenefitType", ref fID_BenefitType, value); }
        }
        string fBenefitTypeName;
        [Indexed(Name = @"Key_BenefitType_BenefitTypeName", Unique = true)]
        public string BenefitTypeName
        {
            get { return fBenefitTypeName; }
            set { SetPropertyValue<string>("BenefitTypeName", ref fBenefitTypeName, value); }
        }
        [Association(@"Request4BenefitMasterReferencesBenefitType", typeof(Request4BenefitMaster))]
        public XPCollection<Request4BenefitMaster> Request4BenefitMasters { get { return GetCollection<Request4BenefitMaster>("Request4BenefitMasters"); } }
        [Association(@"Request4BenefitMaster_NewReferencesBenefitType", typeof(Request4BenefitMaster_New))]
        public XPCollection<Request4BenefitMaster_New> Request4BenefitMaster_News { get { return GetCollection<Request4BenefitMaster_New>("Request4BenefitMaster_News"); } }
    }

}
