//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.PBMS
{

    public partial class DoucmentMaster : XPLiteObject
    {
        string fID_DocumentMaster;
        [Key]
        [Size(10)]
        public string ID_DocumentMaster
        {
            get { return fID_DocumentMaster; }
            set { SetPropertyValue<string>("ID_DocumentMaster", ref fID_DocumentMaster, value); }
        }
        string fDocumentMaster;
        public string DocumentMaster
        {
            get { return fDocumentMaster; }
            set { SetPropertyValue<string>("DocumentMaster", ref fDocumentMaster, value); }
        }
        bool fPreAct;
        public bool PreAct
        {
            get { return fPreAct; }
            set { SetPropertyValue<bool>("PreAct", ref fPreAct, value); }
        }
        bool fRetirement;
        public bool Retirement
        {
            get { return fRetirement; }
            set { SetPropertyValue<bool>("Retirement", ref fRetirement, value); }
        }
        bool fNSITF;
        public bool NSITF
        {
            get { return fNSITF; }
            set { SetPropertyValue<bool>("NSITF", ref fNSITF, value); }
        }
        bool fForeigners;
        public bool Foreigners
        {
            get { return fForeigners; }
            set { SetPropertyValue<bool>("Foreigners", ref fForeigners, value); }
        }
        bool fLossOfEmployment;
        public bool LossOfEmployment
        {
            get { return fLossOfEmployment; }
            set { SetPropertyValue<bool>("LossOfEmployment", ref fLossOfEmployment, value); }
        }
        bool fDeathBeneift;
        public bool DeathBeneift
        {
            get { return fDeathBeneift; }
            set { SetPropertyValue<bool>("DeathBeneift", ref fDeathBeneift, value); }
        }
        bool fAnnuity;
        public bool Annuity
        {
            get { return fAnnuity; }
            set { SetPropertyValue<bool>("Annuity", ref fAnnuity, value); }
        }
        bool fVoluntaryContribution;
        public bool VoluntaryContribution
        {
            get { return fVoluntaryContribution; }
            set { SetPropertyValue<bool>("VoluntaryContribution", ref fVoluntaryContribution, value); }
        }
        bool fGratuityPension;
        public bool GratuityPension
        {
            get { return fGratuityPension; }
            set { SetPropertyValue<bool>("GratuityPension", ref fGratuityPension, value); }
        }
        bool fLegacyBenefit;
        public bool LegacyBenefit
        {
            get { return fLegacyBenefit; }
            set { SetPropertyValue<bool>("LegacyBenefit", ref fLegacyBenefit, value); }
        }
        bool fMissingPerson;
        public bool MissingPerson
        {
            get { return fMissingPerson; }
            set { SetPropertyValue<bool>("MissingPerson", ref fMissingPerson, value); }
        }
        bool fDisability;
        public bool Disability
        {
            get { return fDisability; }
            set { SetPropertyValue<bool>("Disability", ref fDisability, value); }
        }
        bool fOthers_3;
        public bool Others_3
        {
            get { return fOthers_3; }
            set { SetPropertyValue<bool>("Others_3", ref fOthers_3, value); }
        }
        bool fOthers_4;
        public bool Others_4
        {
            get { return fOthers_4; }
            set { SetPropertyValue<bool>("Others_4", ref fOthers_4, value); }
        }
        bool fOthers_5;
        public bool Others_5
        {
            get { return fOthers_5; }
            set { SetPropertyValue<bool>("Others_5", ref fOthers_5, value); }
        }
        bool fOthers_6;
        public bool Others_6
        {
            get { return fOthers_6; }
            set { SetPropertyValue<bool>("Others_6", ref fOthers_6, value); }
        }
        bool fOthers_7;
        public bool Others_7
        {
            get { return fOthers_7; }
            set { SetPropertyValue<bool>("Others_7", ref fOthers_7, value); }
        }
        bool fOthers_8;
        public bool Others_8
        {
            get { return fOthers_8; }
            set { SetPropertyValue<bool>("Others_8", ref fOthers_8, value); }
        }
        bool fOthers_9;
        public bool Others_9
        {
            get { return fOthers_9; }
            set { SetPropertyValue<bool>("Others_9", ref fOthers_9, value); }
        }
        bool fOthers_10;
        public bool Others_10
        {
            get { return fOthers_10; }
            set { SetPropertyValue<bool>("Others_10", ref fOthers_10, value); }
        }
        [Association(@"Request4BenefitDocsReferencesDoucmentMaster", typeof(Request4BenefitDocs))]
        public XPCollection<Request4BenefitDocs> Request4BenefitDocss { get { return GetCollection<Request4BenefitDocs>("Request4BenefitDocss"); } }
    }

}
