//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.PBMS
{

    public partial class EmployerCode : XPLiteObject
    {
        string fEmployerCode1;
        [Key]
        [Size(20)]
        [Persistent(@"EmployerCode")]
        public string EmployerCode1
        {
            get { return fEmployerCode1; }
            set { SetPropertyValue<string>("EmployerCode1", ref fEmployerCode1, value); }
        }
        string fEmployerName;
        [Indexed(Name = @"Key_EmployerCode_Name")]
        [Size(150)]
        public string EmployerName
        {
            get { return fEmployerName; }
            set { SetPropertyValue<string>("EmployerName", ref fEmployerName, value); }
        }
        string fEmployerAddress;
        [Size(250)]
        public string EmployerAddress
        {
            get { return fEmployerAddress; }
            set { SetPropertyValue<string>("EmployerAddress", ref fEmployerAddress, value); }
        }
    }

}
