//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.PBMS
{

    public partial class Request4BenefitMaster_New : XPLiteObject
    {
        Guid fGUID_Request4BenefitMaster;
        [Key(true)]
        public Guid GUID_Request4BenefitMaster
        {
            get { return fGUID_Request4BenefitMaster; }
            set { SetPropertyValue<Guid>("GUID_Request4BenefitMaster", ref fGUID_Request4BenefitMaster, value); }
        }
        int fID_Request4BenefitMaster;
        public int ID_Request4BenefitMaster
        {
            get { return fID_Request4BenefitMaster; }
            set { SetPropertyValue<int>("ID_Request4BenefitMaster", ref fID_Request4BenefitMaster, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fPIN;
        [Size(20)]
        public string PIN
        {
            get { return fPIN; }
            set { SetPropertyValue<string>("PIN", ref fPIN, value); }
        }
        bool fVerifyPIN;
        public bool VerifyPIN
        {
            get { return fVerifyPIN; }
            set { SetPropertyValue<bool>("VerifyPIN", ref fVerifyPIN, value); }
        }
        BenefitType fID_BenefitType;
        [Size(10)]
        [Association(@"Request4BenefitMaster_NewReferencesBenefitType")]
        public BenefitType ID_BenefitType
        {
            get { return fID_BenefitType; }
            set { SetPropertyValue<BenefitType>("ID_BenefitType", ref fID_BenefitType, value); }
        }
        string fID_Scheme;
        [Size(10)]
        public string ID_Scheme
        {
            get { return fID_Scheme; }
            set { SetPropertyValue<string>("ID_Scheme", ref fID_Scheme, value); }
        }
        string fLastEmployerCode;
        [Size(20)]
        public string LastEmployerCode
        {
            get { return fLastEmployerCode; }
            set { SetPropertyValue<string>("LastEmployerCode", ref fLastEmployerCode, value); }
        }
        string fLastEmployerName;
        [Size(150)]
        public string LastEmployerName
        {
            get { return fLastEmployerName; }
            set { SetPropertyValue<string>("LastEmployerName", ref fLastEmployerName, value); }
        }
        DateTime fBirthDate;
        public DateTime BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime>("BirthDate", ref fBirthDate, value); }
        }
        DateTime fRetirementDate;
        public DateTime RetirementDate
        {
            get { return fRetirementDate; }
            set { SetPropertyValue<DateTime>("RetirementDate", ref fRetirementDate, value); }
        }
        DateTime fFirstEmploymentDate;
        public DateTime FirstEmploymentDate
        {
            get { return fFirstEmploymentDate; }
            set { SetPropertyValue<DateTime>("FirstEmploymentDate", ref fFirstEmploymentDate, value); }
        }
        int fAgeAtRetirement;
        public int AgeAtRetirement
        {
            get { return fAgeAtRetirement; }
            set { SetPropertyValue<int>("AgeAtRetirement", ref fAgeAtRetirement, value); }
        }
        char fGender;
        public char Gender
        {
            get { return fGender; }
            set { SetPropertyValue<char>("Gender", ref fGender, value); }
        }
        string fID_RetirementType;
        [Size(4)]
        public string ID_RetirementType
        {
            get { return fID_RetirementType; }
            set { SetPropertyValue<string>("ID_RetirementType", ref fID_RetirementType, value); }
        }
        decimal fAnnualEmolument;
        public decimal AnnualEmolument
        {
            get { return fAnnualEmolument; }
            set { SetPropertyValue<decimal>("AnnualEmolument", ref fAnnualEmolument, value); }
        }
        decimal fAccruedRight;
        public decimal AccruedRight
        {
            get { return fAccruedRight; }
            set { SetPropertyValue<decimal>("AccruedRight", ref fAccruedRight, value); }
        }
        decimal fRSABalance;
        public decimal RSABalance
        {
            get { return fRSABalance; }
            set { SetPropertyValue<decimal>("RSABalance", ref fRSABalance, value); }
        }
        decimal fLumpsumEstimateAmount;
        public decimal LumpsumEstimateAmount
        {
            get { return fLumpsumEstimateAmount; }
            set { SetPropertyValue<decimal>("LumpsumEstimateAmount", ref fLumpsumEstimateAmount, value); }
        }
        decimal fPeriodicEstimateAmount;
        public decimal PeriodicEstimateAmount
        {
            get { return fPeriodicEstimateAmount; }
            set { SetPropertyValue<decimal>("PeriodicEstimateAmount", ref fPeriodicEstimateAmount, value); }
        }
        decimal fPRA_InitialAmount;
        public decimal PRA_InitialAmount
        {
            get { return fPRA_InitialAmount; }
            set { SetPropertyValue<decimal>("PRA_InitialAmount", ref fPRA_InitialAmount, value); }
        }
        decimal fNSITF_To_RSA_Amount;
        public decimal NSITF_To_RSA_Amount
        {
            get { return fNSITF_To_RSA_Amount; }
            set { SetPropertyValue<decimal>("NSITF_To_RSA_Amount", ref fNSITF_To_RSA_Amount, value); }
        }
        decimal fNSITF_From_RSA_Amount;
        public decimal NSITF_From_RSA_Amount
        {
            get { return fNSITF_From_RSA_Amount; }
            set { SetPropertyValue<decimal>("NSITF_From_RSA_Amount", ref fNSITF_From_RSA_Amount, value); }
        }
        decimal fPreAct_Amount;
        public decimal PreAct_Amount
        {
            get { return fPreAct_Amount; }
            set { SetPropertyValue<decimal>("PreAct_Amount", ref fPreAct_Amount, value); }
        }
        string fNationality;
        [Size(50)]
        public string Nationality
        {
            get { return fNationality; }
            set { SetPropertyValue<string>("Nationality", ref fNationality, value); }
        }
        string fID_Resosn4Payment;
        [Size(4)]
        public string ID_Resosn4Payment
        {
            get { return fID_Resosn4Payment; }
            set { SetPropertyValue<string>("ID_Resosn4Payment", ref fID_Resosn4Payment, value); }
        }
        decimal fEmblocAmount;
        public decimal EmblocAmount
        {
            get { return fEmblocAmount; }
            set { SetPropertyValue<decimal>("EmblocAmount", ref fEmblocAmount, value); }
        }
        DateTime fDisEngagementDate;
        public DateTime DisEngagementDate
        {
            get { return fDisEngagementDate; }
            set { SetPropertyValue<DateTime>("DisEngagementDate", ref fDisEngagementDate, value); }
        }
        decimal fRSA_25_Amount;
        public decimal RSA_25_Amount
        {
            get { return fRSA_25_Amount; }
            set { SetPropertyValue<decimal>("RSA_25_Amount", ref fRSA_25_Amount, value); }
        }
        DateTime fDateOfDeath;
        public DateTime DateOfDeath
        {
            get { return fDateOfDeath; }
            set { SetPropertyValue<DateTime>("DateOfDeath", ref fDateOfDeath, value); }
        }
        string fIssueingAuthority;
        public string IssueingAuthority
        {
            get { return fIssueingAuthority; }
            set { SetPropertyValue<string>("IssueingAuthority", ref fIssueingAuthority, value); }
        }
        DateTime fDateOfLetterAdminstraion;
        public DateTime DateOfLetterAdminstraion
        {
            get { return fDateOfLetterAdminstraion; }
            set { SetPropertyValue<DateTime>("DateOfLetterAdminstraion", ref fDateOfLetterAdminstraion, value); }
        }
        string fNamedAdminstrator;
        public string NamedAdminstrator
        {
            get { return fNamedAdminstrator; }
            set { SetPropertyValue<string>("NamedAdminstrator", ref fNamedAdminstrator, value); }
        }
        decimal fLifeInsuranceProceed;
        public decimal LifeInsuranceProceed
        {
            get { return fLifeInsuranceProceed; }
            set { SetPropertyValue<decimal>("LifeInsuranceProceed", ref fLifeInsuranceProceed, value); }
        }
        decimal fContributions;
        public decimal Contributions
        {
            get { return fContributions; }
            set { SetPropertyValue<decimal>("Contributions", ref fContributions, value); }
        }
        decimal fInvestmentIncome;
        public decimal InvestmentIncome
        {
            get { return fInvestmentIncome; }
            set { SetPropertyValue<decimal>("InvestmentIncome", ref fInvestmentIncome, value); }
        }
        string fDeathRemark;
        [Size(SizeAttribute.Unlimited)]
        public string DeathRemark
        {
            get { return fDeathRemark; }
            set { SetPropertyValue<string>("DeathRemark", ref fDeathRemark, value); }
        }
        string fID_InsuranceCompany;
        [Size(10)]
        public string ID_InsuranceCompany
        {
            get { return fID_InsuranceCompany; }
            set { SetPropertyValue<string>("ID_InsuranceCompany", ref fID_InsuranceCompany, value); }
        }
        DateTime fAnnuityBeginDate;
        public DateTime AnnuityBeginDate
        {
            get { return fAnnuityBeginDate; }
            set { SetPropertyValue<DateTime>("AnnuityBeginDate", ref fAnnuityBeginDate, value); }
        }
        decimal fATE_Amount;
        public decimal ATE_Amount
        {
            get { return fATE_Amount; }
            set { SetPropertyValue<decimal>("ATE_Amount", ref fATE_Amount, value); }
        }
        decimal fPremiumAmount;
        public decimal PremiumAmount
        {
            get { return fPremiumAmount; }
            set { SetPropertyValue<decimal>("PremiumAmount", ref fPremiumAmount, value); }
        }
        decimal fPeriodicAnnuityAmount;
        public decimal PeriodicAnnuityAmount
        {
            get { return fPeriodicAnnuityAmount; }
            set { SetPropertyValue<decimal>("PeriodicAnnuityAmount", ref fPeriodicAnnuityAmount, value); }
        }
        decimal fVoluntaryContributionAmount;
        public decimal VoluntaryContributionAmount
        {
            get { return fVoluntaryContributionAmount; }
            set { SetPropertyValue<decimal>("VoluntaryContributionAmount", ref fVoluntaryContributionAmount, value); }
        }
        decimal fTotalVoluntaryContribution;
        public decimal TotalVoluntaryContribution
        {
            get { return fTotalVoluntaryContribution; }
            set { SetPropertyValue<decimal>("TotalVoluntaryContribution", ref fTotalVoluntaryContribution, value); }
        }
        decimal fVC_RequestAmount;
        public decimal VC_RequestAmount
        {
            get { return fVC_RequestAmount; }
            set { SetPropertyValue<decimal>("VC_RequestAmount", ref fVC_RequestAmount, value); }
        }
        decimal fTaxToDeductAmount;
        public decimal TaxToDeductAmount
        {
            get { return fTaxToDeductAmount; }
            set { SetPropertyValue<decimal>("TaxToDeductAmount", ref fTaxToDeductAmount, value); }
        }
        decimal fNet_VC_PayableAmount;
        public decimal Net_VC_PayableAmount
        {
            get { return fNet_VC_PayableAmount; }
            set { SetPropertyValue<decimal>("Net_VC_PayableAmount", ref fNet_VC_PayableAmount, value); }
        }
        decimal fGratuityEnblocAmount;
        public decimal GratuityEnblocAmount
        {
            get { return fGratuityEnblocAmount; }
            set { SetPropertyValue<decimal>("GratuityEnblocAmount", ref fGratuityEnblocAmount, value); }
        }
        decimal fLegacyAmountReceived;
        public decimal LegacyAmountReceived
        {
            get { return fLegacyAmountReceived; }
            set { SetPropertyValue<decimal>("LegacyAmountReceived", ref fLegacyAmountReceived, value); }
        }
        decimal fLegacyAmountPayable;
        public decimal LegacyAmountPayable
        {
            get { return fLegacyAmountPayable; }
            set { SetPropertyValue<decimal>("LegacyAmountPayable", ref fLegacyAmountPayable, value); }
        }
        string fStateOfPosting;
        [Size(15)]
        public string StateOfPosting
        {
            get { return fStateOfPosting; }
            set { SetPropertyValue<string>("StateOfPosting", ref fStateOfPosting, value); }
        }
        decimal fCHARGES;
        public decimal CHARGES
        {
            get { return fCHARGES; }
            set { SetPropertyValue<decimal>("CHARGES", ref fCHARGES, value); }
        }
        decimal fFGNBond;
        public decimal FGNBond
        {
            get { return fFGNBond; }
            set { SetPropertyValue<decimal>("FGNBond", ref fFGNBond, value); }
        }
        decimal fTotalContRemmitted;
        public decimal TotalContRemmitted
        {
            get { return fTotalContRemmitted; }
            set { SetPropertyValue<decimal>("TotalContRemmitted", ref fTotalContRemmitted, value); }
        }
        decimal fLastMonthContRemitted;
        public decimal LastMonthContRemitted
        {
            get { return fLastMonthContRemitted; }
            set { SetPropertyValue<decimal>("LastMonthContRemitted", ref fLastMonthContRemitted, value); }
        }
        decimal fTotalUnits;
        public decimal TotalUnits
        {
            get { return fTotalUnits; }
            set { SetPropertyValue<decimal>("TotalUnits", ref fTotalUnits, value); }
        }
        decimal fCurrentUnitRate;
        public decimal CurrentUnitRate
        {
            get { return fCurrentUnitRate; }
            set { SetPropertyValue<decimal>("CurrentUnitRate", ref fCurrentUnitRate, value); }
        }
        decimal fTotalAnnualSalary;
        public decimal TotalAnnualSalary
        {
            get { return fTotalAnnualSalary; }
            set { SetPropertyValue<decimal>("TotalAnnualSalary", ref fTotalAnnualSalary, value); }
        }
        decimal fLumpSumWithdrawal;
        public decimal LumpSumWithdrawal
        {
            get { return fLumpSumWithdrawal; }
            set { SetPropertyValue<decimal>("LumpSumWithdrawal", ref fLumpSumWithdrawal, value); }
        }
        decimal fMonthlyProgWithdrawal;
        public decimal MonthlyProgWithdrawal
        {
            get { return fMonthlyProgWithdrawal; }
            set { SetPropertyValue<decimal>("MonthlyProgWithdrawal", ref fMonthlyProgWithdrawal, value); }
        }
        decimal fNIL_LumpSumWithdrawal;
        public decimal NIL_LumpSumWithdrawal
        {
            get { return fNIL_LumpSumWithdrawal; }
            set { SetPropertyValue<decimal>("NIL_LumpSumWithdrawal", ref fNIL_LumpSumWithdrawal, value); }
        }
        decimal fMaxMonthlyProgWithdrawal;
        public decimal MaxMonthlyProgWithdrawal
        {
            get { return fMaxMonthlyProgWithdrawal; }
            set { SetPropertyValue<decimal>("MaxMonthlyProgWithdrawal", ref fMaxMonthlyProgWithdrawal, value); }
        }
        decimal fProgWithdrawalArrears;
        public decimal ProgWithdrawalArrears
        {
            get { return fProgWithdrawalArrears; }
            set { SetPropertyValue<decimal>("ProgWithdrawalArrears", ref fProgWithdrawalArrears, value); }
        }
        decimal fTotalBenefitPayable;
        public decimal TotalBenefitPayable
        {
            get { return fTotalBenefitPayable; }
            set { SetPropertyValue<decimal>("TotalBenefitPayable", ref fTotalBenefitPayable, value); }
        }
        string fDedicatedBank;
        [Size(50)]
        public string DedicatedBank
        {
            get { return fDedicatedBank; }
            set { SetPropertyValue<string>("DedicatedBank", ref fDedicatedBank, value); }
        }
        int fAccountNumber;
        public int AccountNumber
        {
            get { return fAccountNumber; }
            set { SetPropertyValue<int>("AccountNumber", ref fAccountNumber, value); }
        }
        int fRoutingNumber;
        public int RoutingNumber
        {
            get { return fRoutingNumber; }
            set { SetPropertyValue<int>("RoutingNumber", ref fRoutingNumber, value); }
        }
        char fStatus;
        public char Status
        {
            get { return fStatus; }
            set { SetPropertyValue<char>("Status", ref fStatus, value); }
        }
        string fComments;
        [Size(SizeAttribute.Unlimited)]
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>("Comments", ref fComments, value); }
        }
        string fID_Branch;
        [Size(4)]
        public string ID_Branch
        {
            get { return fID_Branch; }
            set { SetPropertyValue<string>("ID_Branch", ref fID_Branch, value); }
        }
        string fCapturedBy;
        [Size(50)]
        public string CapturedBy
        {
            get { return fCapturedBy; }
            set { SetPropertyValue<string>("CapturedBy", ref fCapturedBy, value); }
        }
        DateTime fCreatedDate;
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>("CreatedDate", ref fCreatedDate, value); }
        }
        DateTime fModifiedDate;
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>("ModifiedDate", ref fModifiedDate, value); }
        }
        bool fRequestComplted;
        public bool RequestComplted
        {
            get { return fRequestComplted; }
            set { SetPropertyValue<bool>("RequestComplted", ref fRequestComplted, value); }
        }
        bool fTransmitionOkay;
        public bool TransmitionOkay
        {
            get { return fTransmitionOkay; }
            set { SetPropertyValue<bool>("TransmitionOkay", ref fTransmitionOkay, value); }
        }
        DateTime fTransmitedDate;
        public DateTime TransmitedDate
        {
            get { return fTransmitedDate; }
            set { SetPropertyValue<DateTime>("TransmitedDate", ref fTransmitedDate, value); }
        }
        DateTime fNextApponintmentDate;
        public DateTime NextApponintmentDate
        {
            get { return fNextApponintmentDate; }
            set { SetPropertyValue<DateTime>("NextApponintmentDate", ref fNextApponintmentDate, value); }
        }
        int fNoOfAreas;
        public int NoOfAreas
        {
            get { return fNoOfAreas; }
            set { SetPropertyValue<int>("NoOfAreas", ref fNoOfAreas, value); }
        }
        string fPENCOMRefNo;
        [Size(50)]
        public string PENCOMRefNo
        {
            get { return fPENCOMRefNo; }
            set { SetPropertyValue<string>("PENCOMRefNo", ref fPENCOMRefNo, value); }
        }
        decimal fQuarterlyProgWithdrawal;
        public decimal QuarterlyProgWithdrawal
        {
            get { return fQuarterlyProgWithdrawal; }
            set { SetPropertyValue<decimal>("QuarterlyProgWithdrawal", ref fQuarterlyProgWithdrawal, value); }
        }
    }

}
