//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.PBMS
{

    public partial class Request4BenefitDocs : XPLiteObject
    {
        Guid fGUID_Request4BenefitDocs;
        [Key(true)]
        public Guid GUID_Request4BenefitDocs
        {
            get { return fGUID_Request4BenefitDocs; }
            set { SetPropertyValue<Guid>("GUID_Request4BenefitDocs", ref fGUID_Request4BenefitDocs, value); }
        }
        Request4BenefitMaster fGUID_Request4BenefitMaster;
        [Association(@"Request4BenefitDocsReferencesRequest4BenefitMaster")]
        public Request4BenefitMaster GUID_Request4BenefitMaster
        {
            get { return fGUID_Request4BenefitMaster; }
            set { SetPropertyValue<Request4BenefitMaster>("GUID_Request4BenefitMaster", ref fGUID_Request4BenefitMaster, value); }
        }
        int fID_Request4BenefitDocs;
        public int ID_Request4BenefitDocs
        {
            get { return fID_Request4BenefitDocs; }
            set { SetPropertyValue<int>("ID_Request4BenefitDocs", ref fID_Request4BenefitDocs, value); }
        }
        DoucmentMaster fID_DocumentMaster;
        [Size(10)]
        [Association(@"Request4BenefitDocsReferencesDoucmentMaster")]
        public DoucmentMaster ID_DocumentMaster
        {
            get { return fID_DocumentMaster; }
            set { SetPropertyValue<DoucmentMaster>("ID_DocumentMaster", ref fID_DocumentMaster, value); }
        }
        bool fSubmited;
        public bool Submited
        {
            get { return fSubmited; }
            set { SetPropertyValue<bool>("Submited", ref fSubmited, value); }
        }
        DateTime fSubmitedDate;
        public DateTime SubmitedDate
        {
            get { return fSubmitedDate; }
            set { SetPropertyValue<DateTime>("SubmitedDate", ref fSubmitedDate, value); }
        }
        bool fScanned;
        public bool Scanned
        {
            get { return fScanned; }
            set { SetPropertyValue<bool>("Scanned", ref fScanned, value); }
        }
        DateTime fScannedDate;
        public DateTime ScannedDate
        {
            get { return fScannedDate; }
            set { SetPropertyValue<DateTime>("ScannedDate", ref fScannedDate, value); }
        }
        string fScanFileName;
        public string ScanFileName
        {
            get { return fScanFileName; }
            set { SetPropertyValue<string>("ScanFileName", ref fScanFileName, value); }
        }
        bool fDocumentCompleted;
        public bool DocumentCompleted
        {
            get { return fDocumentCompleted; }
            set { SetPropertyValue<bool>("DocumentCompleted", ref fDocumentCompleted, value); }
        }
        bool fTransmited;
        public bool Transmited
        {
            get { return fTransmited; }
            set { SetPropertyValue<bool>("Transmited", ref fTransmited, value); }
        }
        DateTime fCreatedDate;
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>("CreatedDate", ref fCreatedDate, value); }
        }
        DateTime fModifiedDate;
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>("ModifiedDate", ref fModifiedDate, value); }
        }
        bool fTransmitionOkay;
        public bool TransmitionOkay
        {
            get { return fTransmitionOkay; }
            set { SetPropertyValue<bool>("TransmitionOkay", ref fTransmitionOkay, value); }
        }
        DateTime fTransmitedDate;
        public DateTime TransmitedDate
        {
            get { return fTransmitedDate; }
            set { SetPropertyValue<DateTime>("TransmitedDate", ref fTransmitedDate, value); }
        }
        string fComments;
        [Size(SizeAttribute.Unlimited)]
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>("Comments", ref fComments, value); }
        }
    }

}
