//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.PBMS
{

    public partial class RSAMaster : XPLiteObject
    {
        Guid fID_RSAMaster;
        public Guid ID_RSAMaster
        {
            get { return fID_RSAMaster; }
            set { SetPropertyValue<Guid>("ID_RSAMaster", ref fID_RSAMaster, value); }
        }
        string fPIN;
        [Key]
        [Size(20)]
        public string PIN
        {
            get { return fPIN; }
            set { SetPropertyValue<string>("PIN", ref fPIN, value); }
        }
        string fFullName;
        [Size(150)]
        public string FullName
        {
            get { return fFullName; }
            set { SetPropertyValue<string>("FullName", ref fFullName, value); }
        }
        string fEmployerCode;
        [Size(20)]
        public string EmployerCode
        {
            get { return fEmployerCode; }
            set { SetPropertyValue<string>("EmployerCode", ref fEmployerCode, value); }
        }
        DateTime fDateOfBirth;
        public DateTime DateOfBirth
        {
            get { return fDateOfBirth; }
            set { SetPropertyValue<DateTime>("DateOfBirth", ref fDateOfBirth, value); }
        }
        char fGender;
        public char Gender
        {
            get { return fGender; }
            set { SetPropertyValue<char>("Gender", ref fGender, value); }
        }
        decimal fRSABalance;
        public decimal RSABalance
        {
            get { return fRSABalance; }
            set { SetPropertyValue<decimal>("RSABalance", ref fRSABalance, value); }
        }
    }

}
