//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.PBMS
{

    public partial class StateLocalGov : XPLiteObject
    {
        string fState;
        [Size(20)]
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>("State", ref fState, value); }
        }
        string fLocalGovernment;
        [Size(50)]
        public string LocalGovernment
        {
            get { return fLocalGovernment; }
            set { SetPropertyValue<string>("LocalGovernment", ref fLocalGovernment, value); }
        }
        int fLGID;
        [Key(true)]
        public int LGID
        {
            get { return fLGID; }
            set { SetPropertyValue<int>("LGID", ref fLGID, value); }
        }
    }

}
