//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.PBMS
{

    public partial class state : XPLiteObject
    {
        string fstate1;
        [Key]
        [Size(20)]
        [Persistent(@"state")]
        public string state1
        {
            get { return fstate1; }
            set { SetPropertyValue<string>("state1", ref fstate1, value); }
        }
    }

}
