//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBams.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iBams.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Penguins {
            get {
                object obj = ResourceManager.GetObject("Penguins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dossier1
        {
            get
            {
                object obj = ResourceManager.GetObject("dossier1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eco28
        {
            get
            {
                object obj = ResourceManager.GetObject("eco28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit10
        {
            get
            {
                object obj = ResourceManager.GetObject("exit10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit8
        {
            get
            {
                object obj = ResourceManager.GetObject("exit8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap family26
        {
            get
            {
                object obj = ResourceManager.GetObject("family26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap halloween195
        {
            get
            {
                object obj = ResourceManager.GetObject("halloween195", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information18
        {
            get
            {
                object obj = ResourceManager.GetObject("information18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username and password..
        /// </summary>
        internal static string Login_Validation_Message
        {
            get
            {
                return ResourceManager.GetString("Login_Validation_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Denied!.
        /// </summary>
        internal static string Login_Validation_Message_AccessDenied
        {
            get
            {
                return ResourceManager.GetString("Login_Validation_Message_AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        internal static string Login_Validation_Message_InvalidCredentials
        {
            get
            {
                return ResourceManager.GetString("Login_Validation_Message_InvalidCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Group. Contact Administrator.
        /// </summary>
        internal static string Login_Validation_Message_NoGroup
        {
            get
            {
                return ResourceManager.GetString("Login_Validation_Message_NoGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login - Message.
        /// </summary>
        internal static string Login_Validation_Message_Title
        {
            get
            {
                return ResourceManager.GetString("Login_Validation_Message_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Vendor Credentials.
        /// </summary>
        internal static string Login_Validation_Message_Vendor
        {
            get
            {
                return ResourceManager.GetString("Login_Validation_Message_Vendor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap male107
        {
            get
            {
                object obj = ResourceManager.GetObject("male107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap parasol
        {
            get
            {
                object obj = ResourceManager.GetObject("parasol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings48
        {
            get
            {
                object obj = ResourceManager.GetObject("settings48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sitting6
        {
            get
            {
                object obj = ResourceManager.GetObject("sitting6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wheelchair1
        {
            get
            {
                object obj = ResourceManager.GetObject("wheelchair1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
