//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class ButtonApproval : XPLiteObject
    {
        int fID_ButtonApproval;
        [Key(true)]
        public int ID_ButtonApproval
        {
            get { return fID_ButtonApproval; }
            set { SetPropertyValue<int>("ID_ButtonApproval", ref fID_ButtonApproval, value); }
        }
        string fButtonCaption;
        [Size(50)]
        public string ButtonCaption
        {
            get { return fButtonCaption; }
            set { SetPropertyValue<string>("ButtonCaption", ref fButtonCaption, value); }
        }
        string fAllowedUser;
        [Size(50)]
        public string AllowedUser
        {
            get { return fAllowedUser; }
            set { SetPropertyValue<string>("AllowedUser", ref fAllowedUser, value); }
        }
        string fPageName;
        [Size(50)]
        public string PageName
        {
            get { return fPageName; }
            set { SetPropertyValue<string>("PageName", ref fPageName, value); }
        }
    }

}
