//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class ControlType : XPLiteObject
    {
        int fID_ControlType;
        [Key(true)]
        public int ID_ControlType
        {
            get { return fID_ControlType; }
            set { SetPropertyValue<int>("ID_ControlType", ref fID_ControlType, value); }
        }
        string fControlType1;
        [Size(50)]
        [Persistent(@"ControlType")]
        public string ControlType1
        {
            get { return fControlType1; }
            set { SetPropertyValue<string>("ControlType1", ref fControlType1, value); }
        }
        string fControlProperty;
        [Size(50)]
        public string ControlProperty
        {
            get { return fControlProperty; }
            set { SetPropertyValue<string>("ControlProperty", ref fControlProperty, value); }
        }
        string fControlIdentifier;
        [Size(50)]
        public string ControlIdentifier
        {
            get { return fControlIdentifier; }
            set { SetPropertyValue<string>("ControlIdentifier", ref fControlIdentifier, value); }
        }
    }

}
