//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class ControlApproval : XPLiteObject
    {
        int fID_ControlApproval;
        [Key(true)]
        public int ID_ControlApproval
        {
            get { return fID_ControlApproval; }
            set { SetPropertyValue<int>("ID_ControlApproval", ref fID_ControlApproval, value); }
        }
        string fControlName;
        [Size(50)]
        public string ControlName
        {
            get { return fControlName; }
            set { SetPropertyValue<string>("ControlName", ref fControlName, value); }
        }
        string fID_ControlType;
        [Size(50)]
        public string ID_ControlType
        {
            get { return fID_ControlType; }
            set { SetPropertyValue<string>("ID_ControlType", ref fID_ControlType, value); }
        }
        string fViewName;
        [Size(50)]
        public string ViewName
        {
            get { return fViewName; }
            set { SetPropertyValue<string>("ViewName", ref fViewName, value); }
        }
        string fAllowedUserGroup;
        [Size(10)]
        public string AllowedUserGroup
        {
            get { return fAllowedUserGroup; }
            set { SetPropertyValue<string>("AllowedUserGroup", ref fAllowedUserGroup, value); }
        }
    }

}
