//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class DefaultResources : XPLiteObject
    {
        int fID_Resource;
        [Key(true)]
        public int ID_Resource
        {
            get { return fID_Resource; }
            set { SetPropertyValue<int>("ID_Resource", ref fID_Resource, value); }
        }
        string fID_Application;
        [Size(50)]
        public string ID_Application
        {
            get { return fID_Application; }
            set { SetPropertyValue<string>("ID_Application", ref fID_Application, value); }
        }
        string fResourceName;
        public string ResourceName
        {
            get { return fResourceName; }
            set { SetPropertyValue<string>("ResourceName", ref fResourceName, value); }
        }
    }

}
