//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class LangDictionary : XPLiteObject
    {
        string fEnglish;
        [Key]
        public string English
        {
            get { return fEnglish; }
            set { SetPropertyValue<string>("English", ref fEnglish, value); }
        }
        string fYoruba;
        public string Yoruba
        {
            get { return fYoruba; }
            set { SetPropertyValue<string>("Yoruba", ref fYoruba, value); }
        }
        string fIgbo;
        public string Igbo
        {
            get { return fIgbo; }
            set { SetPropertyValue<string>("Igbo", ref fIgbo, value); }
        }
        string fHausa;
        public string Hausa
        {
            get { return fHausa; }
            set { SetPropertyValue<string>("Hausa", ref fHausa, value); }
        }
    }

}
