//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class Preferences : XPLiteObject
    {
        string fVendorLogin;
        [Size(50)]
        public string VendorLogin
        {
            get { return fVendorLogin; }
            set { SetPropertyValue<string>("VendorLogin", ref fVendorLogin, value); }
        }
        string fVendorPassword;
        [Size(50)]
        public string VendorPassword
        {
            get { return fVendorPassword; }
            set { SetPropertyValue<string>("VendorPassword", ref fVendorPassword, value); }
        }
        bool fVendorEnabled;
        public bool VendorEnabled
        {
            get { return fVendorEnabled; }
            set { SetPropertyValue<bool>("VendorEnabled", ref fVendorEnabled, value); }
        }
        string fDefaultPassword;
        [Size(50)]
        public string DefaultPassword
        {
            get { return fDefaultPassword; }
            set { SetPropertyValue<string>("DefaultPassword", ref fDefaultPassword, value); }
        }
        string fVendorName;
        [Size(50)]
        public string VendorName
        {
            get { return fVendorName; }
            set { SetPropertyValue<string>("VendorName", ref fVendorName, value); }
        }
        string fMoneyBookDatabase;
        [Size(50)]
        public string MoneyBookDatabase
        {
            get { return fMoneyBookDatabase; }
            set { SetPropertyValue<string>("MoneyBookDatabase", ref fMoneyBookDatabase, value); }
        }
        int fMinimumPasswordLenght;
        public int MinimumPasswordLenght
        {
            get { return fMinimumPasswordLenght; }
            set { SetPropertyValue<int>("MinimumPasswordLenght", ref fMinimumPasswordLenght, value); }
        }
        bool fPasswordExpiry;
        public bool PasswordExpiry
        {
            get { return fPasswordExpiry; }
            set { SetPropertyValue<bool>("PasswordExpiry", ref fPasswordExpiry, value); }
        }
        int fPasswordExpiryDays;
        public int PasswordExpiryDays
        {
            get { return fPasswordExpiryDays; }
            set { SetPropertyValue<int>("PasswordExpiryDays", ref fPasswordExpiryDays, value); }
        }
        int fDaysWarnedB4PwdExpires;
        public int DaysWarnedB4PwdExpires
        {
            get { return fDaysWarnedB4PwdExpires; }
            set { SetPropertyValue<int>("DaysWarnedB4PwdExpires", ref fDaysWarnedB4PwdExpires, value); }
        }
        int fMaxLoginAttempts;
        public int MaxLoginAttempts
        {
            get { return fMaxLoginAttempts; }
            set { SetPropertyValue<int>("MaxLoginAttempts", ref fMaxLoginAttempts, value); }
        }
        bool fStrongPassword;
        public bool StrongPassword
        {
            get { return fStrongPassword; }
            set { SetPropertyValue<bool>("StrongPassword", ref fStrongPassword, value); }
        }
        int fMaxNumberOfSavedPwdPerUser;
        public int MaxNumberOfSavedPwdPerUser
        {
            get { return fMaxNumberOfSavedPwdPerUser; }
            set { SetPropertyValue<int>("MaxNumberOfSavedPwdPerUser", ref fMaxNumberOfSavedPwdPerUser, value); }
        }
        bool fDisableAllSecurity;
        public bool DisableAllSecurity
        {
            get { return fDisableAllSecurity; }
            set { SetPropertyValue<bool>("DisableAllSecurity", ref fDisableAllSecurity, value); }
        }
        int fID_Preferences;
        [Key(true)]
        public int ID_Preferences
        {
            get { return fID_Preferences; }
            set { SetPropertyValue<int>("ID_Preferences", ref fID_Preferences, value); }
        }
    }

}
