//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class Users : XPLiteObject
    {
        int fID_User;
        [Key(true)]
        public int ID_User
        {
            get { return fID_User; }
            set { SetPropertyValue<int>("ID_User", ref fID_User, value); }
        }
        int fID_Group;
        public int ID_Group
        {
            get { return fID_Group; }
            set { SetPropertyValue<int>("ID_Group", ref fID_Group, value); }
        }
        string fID_Login;
        [Indexed(Name = @"UD_User", Unique = true)]
        [Size(50)]
        public string ID_Login
        {
            get { return fID_Login; }
            set { SetPropertyValue<string>("ID_Login", ref fID_Login, value); }
        }
        string fPassword;
        [Size(50)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>("Password", ref fPassword, value); }
        }
        bool fDefaultPassword;
        public bool DefaultPassword
        {
            get { return fDefaultPassword; }
            set { SetPropertyValue<bool>("DefaultPassword", ref fDefaultPassword, value); }
        }
        string fFirstName;
        [Size(400)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>("FirstName", ref fFirstName, value); }
        }
        string fLastName;
        [Size(400)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>("LastName", ref fLastName, value); }
        }
        bool fEnabled;
        public bool Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<bool>("Enabled", ref fEnabled, value); }
        }
        string fInitials;
        [Size(50)]
        public string Initials
        {
            get { return fInitials; }
            set { SetPropertyValue<string>("Initials", ref fInitials, value); }
        }
        string fPhone;
        [Size(400)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>("Phone", ref fPhone, value); }
        }
        string fPhotoPath;
        [Size(50)]
        public string PhotoPath
        {
            get { return fPhotoPath; }
            set { SetPropertyValue<string>("PhotoPath", ref fPhotoPath, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>("Notes", ref fNotes, value); }
        }
        string fCashBoxID;
        [Size(10)]
        public string CashBoxID
        {
            get { return fCashBoxID; }
            set { SetPropertyValue<string>("CashBoxID", ref fCashBoxID, value); }
        }
        string fSecret_Question;
        [Size(SizeAttribute.Unlimited)]
        public string Secret_Question
        {
            get { return fSecret_Question; }
            set { SetPropertyValue<string>("Secret_Question", ref fSecret_Question, value); }
        }
        string fSecret_Answer;
        [Size(50)]
        public string Secret_Answer
        {
            get { return fSecret_Answer; }
            set { SetPropertyValue<string>("Secret_Answer", ref fSecret_Answer, value); }
        }
    }

}
