//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class UserGroup : XPLiteObject
    {
        int fID_Group;
        public int ID_Group
        {
            get { return fID_Group; }
            set { SetPropertyValue<int>("ID_Group", ref fID_Group, value); }
        }
        string fGroupName;
        [Key]
        [Size(50)]
        public string GroupName
        {
            get { return fGroupName; }
            set { SetPropertyValue<string>("GroupName", ref fGroupName, value); }
        }
        bool fEnabled;
        public bool Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<bool>("Enabled", ref fEnabled, value); }
        }
        string fID_Branch;
        [Size(50)]
        public string ID_Branch
        {
            get { return fID_Branch; }
            set { SetPropertyValue<string>("ID_Branch", ref fID_Branch, value); }
        }
    }

}
