//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PBMSModel.Ibs_Security
{

    public partial class WorkPeriod : XPLiteObject
    {
        long fID_WorkPeriod;
        [Key(true)]
        public long ID_WorkPeriod
        {
            get { return fID_WorkPeriod; }
            set { SetPropertyValue<long>("ID_WorkPeriod", ref fID_WorkPeriod, value); }
        }
        int fID_Group;
        [Indexed(Name = @"UQ_ID_Group", Unique = true)]
        public int ID_Group
        {
            get { return fID_Group; }
            set { SetPropertyValue<int>("ID_Group", ref fID_Group, value); }
        }
        string fWorkDays;
        [Size(30)]
        public string WorkDays
        {
            get { return fWorkDays; }
            set { SetPropertyValue<string>("WorkDays", ref fWorkDays, value); }
        }
        int fStartHour;
        public int StartHour
        {
            get { return fStartHour; }
            set { SetPropertyValue<int>("StartHour", ref fStartHour, value); }
        }
        int fEndHour;
        public int EndHour
        {
            get { return fEndHour; }
            set { SetPropertyValue<int>("EndHour", ref fEndHour, value); }
        }
        DateTime fDeactivateDate;
        public DateTime DeactivateDate
        {
            get { return fDeactivateDate; }
            set { SetPropertyValue<DateTime>("DeactivateDate", ref fDeactivateDate, value); }
        }
    }

}
